---
title: "R Notebook"
output: html_notebook
---

```{r warning=FALSE}
library(tidyverse)
```

# EDA dos dados de estimativa de insatisfação

## Subtítulo

Dados coletados na sala. 

```{r}
avaliacoes = read_csv("../../data/experimento-avaliacao-humana/experimento-de-avaliacao.csv", 
                      col_types = "ccd")


avaliacoes = avaliacoes %>% 
    select(avaliador = `Sua matrícula`, 
           id_reclamacao = `Id da reclamação`, 
           insatisfacao = Insatisfação)

# avaliacoes %>% 
#     group_by(id_reclamacao) %>% 
#     ggplot(aes(reorder(id_reclamacao, insatisfacao,FUN = median), insatisfacao, colour = id_reclamacao)) +
# geom_point(color = "darkorange") +
# coord_flip()

# ggplot(avaliacoes) + 
#   geom_bar(mapping = aes(x = insatisfacao))

# ggplot(avaliacoes) + 
#   geom_bar(mapping = aes(x = avaliador))  

# ggplot(avaliacoes, aes(x = id_reclamacao, y = avaliador)) + 
#   geom_jitter(width = .1, height = 0, alpha = .6)

avaliacoes %>%
  filter(insatisfacao > 3) %>% 
  ggplot() +
  geom_point(mapping = aes(x = id_reclamacao, 
                           y = avaliador), 
             alpha = 0.7) 

avaliacoes %>% filter(insatisfacao > 3) %>% ggplot(data = avaliacoes) +
  geom_point(mapping = aes(x = id_reclamacao, y = avaliador), 
             alpha = 0.7) 
```

## Limpeza

Explicar

```{r}
avaliacoes = avaliacoes %>% 
    filter(! (id_reclamacao %in% 1:5 ))
```


## Outro subtítulo

```{r}
avaliacoes %>% 
    group_by(id_reclamacao) %>% 
    count() %>% 
    ggplot(aes("reclamacoes", n)) + 
    geom_jitter(width = .05, alpha = .7)

avaliacoes %>% 
    group_by(id_reclamacao) %>% 
    count() %>%
    ungroup() %>% 
    summarise(media = mean(n), 
              mediana = median(n))


```

```{r}
avaliacoes %>% 
    ggplot(aes(x = reorder(id_reclamacao, insatisfacao, fun = median), y = insatisfacao)) + 
    geom_boxplot() #+     geom_jitter(width = .1, alpha = .7)



```


```{r}
avaliacoes %>% 
    group_by(id_reclamacao) %>% 
    ggplot(aes(reorder(id_reclamacao, insatisfacao,FUN = median), insatisfacao, colour = id_reclamacao)) + 
    geom_jitter()
```

